apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: build-rhivos-template
  title: Build RHIVOS Image Template
  description: Create a RHIVOS Image
  tags:
    - basic
    - RHIVOS
    - automotive
spec:
  owner: automotive-collection
  type: builder
  parameters:
    - title: Provide basic information for the RHIVOS build
      required:
        - manifest_name
        - manifest_location
        - artifact_id
      properties:
        manifest_name:
          title: Manifest
          type: string
          description: Name of the manifest file
          default: devel
          #ui:field: EntityNamePicker
          maxLength: 40
        manifest_location:
          title: Location
          type: string
          default: ./manifests
          description: Manifest file location
        artifact_id:
          title: Artifact Id
          type: string
          default: devel-build
          description: RHIVOS Artifact Id
        description:
          title: Description
          type: string
          description: Help others understand what this RHIVOS build is for.
          default: RHIVOS development image
    - title: Build parameters
      required:
        - distro
        - arch
        - target
        - mode
        - export_format
      properties:
        distro:
          title: Distro
          type: string
          default: autosd
          enum:
            - autosd
            - cs9
        arch:
          title: Architecture
          type: string
          default: aarch64
          enum:
            - aarch64
            - x86_64
        target:
          title: Target
          type: string
          default: rpi4
          enum:
            - rpi4
            - qemu
        mode:
          title: Target
          type: string
          default: package
          enum:
            - package
            - image
        export_format:
          title: Target
          type: string
          default: image
          enum:
            - image
            - qcow2
            - container
  steps:
    - id: template
      name: Fetch Skeleton + Templates
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          manifest_name: ${{ parameters.manifest_name }}
          manifest_location: ${{ parameters.manifest_location }}
          artifact_id: ${{ parameters.artifact_id }}
          description: ${{ parameters.description }}
          distro: ${{ parameters.distro }}
          arch: ${{ parameters.arch }}
          target: ${{ parameters.target }}
          mode: ${{ parameters.mode }}
          export_format: ${{ parameters.export_format }}
          # computed values
          namespace: ${{ parameters.artifact_id }}-build
          owner: ${{ user.entity.metadata.name }}
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.artifact_id }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.artifact_id}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"